version: '3'
services:
  app:
    build: .
    volumes:
    - .:/app
    ports:
      - "6000:6000"   # Change the port mapping as needed
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"