version: "3.9"

services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  inserter:
    build: 
      context: .
      dockerfile: Dockerfile.python
    container_name: inserter
    depends_on:
      - influxdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    platform: linux/amd64
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=my-bucket
    command: python3 main.py

volumes:
  influxdb_data: