# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to /app
COPY . .

# Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r fix_md/requirements.txt


# # Define the default command to run your app
ENTRYPOINT ["sh", "-c", "sleep infinity"]