version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./ssl:/certs"  # Mapping your SSL directory
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/default.config:/etc/nginx/conf.d/default.config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`invoicehq.com.au`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"

      
  # hasura:
  #   image: hasura/graphql-engine:v2.27.0
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     HASURA_GRAPHQL_DATABASE_URL: "postgres://user:password@db:5432/mydb"
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  #     HASURA_GRAPHQL_DEV_MODE: "true"
  #     HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"your-secret-key"}'
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.hasura.rule=Host(`invoicehq.com.au`) && PathPrefix(`/graphql`)"
  #     - "traefik.http.routers.hasura.entrypoints=web,websecure"
  #     - "traefik.http.routers.hasura.tls.certresolver=myresolver"
  #     - "traefik.http.services.hasura.loadbalancer.server.port=8080"