version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      # - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100000M
      - PMA_HOSTS=stw7v6jjq3.cr7krjheaecg.us-east-1.rds.amazonaws.com,host.docker.internal,invoicehq-prod-db-2024-v2.cluster-cr7krjheaecg.us-east-1.rds.amazonaws.com