version: "3.9"

services:
  app:
    image: monica:4.1.2-apache
    ports:
      # - 9000:80
      - 80:80
    depends_on:
      - db
    environment:
      - APP_KEY=base64:MOo36I4CYrdY0UPHf3GGXy0fqCfm3eJKcBOmptra9Co= # Generate with `echo -n 'base64:'; openssl rand -base64 32`
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
      - APP_DISABLE_SIGNUP=false
      # - APP_ENV=production
    volumes:
      - ./monica_documents/:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - UPLOAD_LIMIT=100000M

volumes:
  mysql:
    name: mysql